// <auto-generated />
namespace Iris.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ItemCollaction : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ItemCollaction));
        
        string IMigrationMetadata.Id
        {
            get { return "202005211459002_ItemCollaction"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
