// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static partial class T4
{
    static readonly AdminPanelClass s_AdminPanel = new AdminPanelClass();
    public static AdminPanelClass AdminPanel { get { return s_AdminPanel; } }
    static readonly ItemsClass s_Items = new ItemsClass();
    public static ItemsClass Items { get { return s_Items; } }
    static readonly ItemTypeClass s_ItemType = new ItemTypeClass();
    public static ItemTypeClass ItemType { get { return s_ItemType; } }
    static readonly PageClass s_Page = new PageClass();
    public static PageClass Page { get { return s_Page; } }
    static readonly PostClass s_Post = new PostClass();
    public static PostClass Post { get { return s_Post; } }
    static readonly PostCategoryClass s_PostCategory = new PostCategoryClass();
    public static PostCategoryClass PostCategory { get { return s_PostCategory; } }
    static readonly ProductClass s_Product = new ProductClass();
    public static ProductClass Product { get { return s_Product; } }
    static readonly ProductCategoryClass s_ProductCategory = new ProductCategoryClass();
    public static ProductCategoryClass ProductCategory { get { return s_ProductCategory; } }
    static readonly ShoppingCartClass s_ShoppingCart = new ShoppingCartClass();
    public static ShoppingCartClass ShoppingCart { get { return s_ShoppingCart; } }
    static readonly SiteSettingClass s_SiteSetting = new SiteSettingClass();
    public static SiteSettingClass SiteSetting { get { return s_SiteSetting; } }
    static readonly SlideShowClass s_SlideShow = new SlideShowClass();
    public static SlideShowClass SlideShow { get { return s_SlideShow; } }
    static readonly UserClass s_User = new UserClass();
    public static UserClass User { get { return s_User; } }
    public static T4MVC.AccountController Account = new T4MVC.AccountController();
    public static T4MVC.HomeController Home = new T4MVC.HomeController();
    public static T4MVC.SharedController Shared = new T4MVC.SharedController();
    public static T4MVC.WidgetsController Widgets = new T4MVC.WidgetsController();
}

namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class AdminPanelClass
    {
        public readonly string Name = "AdminPanel";
        public T4MVC.AdminPanel.DashboardController Dashboard = new T4MVC.AdminPanel.DashboardController();
        public T4MVC.AdminPanel.SharedController Shared = new T4MVC.AdminPanel.SharedController();
    }
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class ItemsClass
    {
        public readonly string Name = "Items";
        public T4MVC.Items.AdminController Admin = new T4MVC.Items.AdminController();
        public T4MVC.Items.SharedController Shared = new T4MVC.Items.SharedController();
    }
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class ItemTypeClass
    {
        public readonly string Name = "ItemType";
        public T4MVC.ItemType.AdminController Admin = new T4MVC.ItemType.AdminController();
        public T4MVC.ItemType.SharedController Shared = new T4MVC.ItemType.SharedController();
    }
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class PageClass
    {
        public readonly string Name = "Page";
        public T4MVC.Page.AdminController Admin = new T4MVC.Page.AdminController();
    }
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class PostClass
    {
        public readonly string Name = "Post";
        public T4MVC.Post.AdminController Admin = new T4MVC.Post.AdminController();
        public T4MVC.Post.HomeController Home = new T4MVC.Post.HomeController();
        public T4MVC.Post.SharedController Shared = new T4MVC.Post.SharedController();
        public T4MVC.Post.WidgetsController Widgets = new T4MVC.Post.WidgetsController();
    }
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class PostCategoryClass
    {
        public readonly string Name = "PostCategory";
        public T4MVC.PostCategory.AdminController Admin = new T4MVC.PostCategory.AdminController();
        public T4MVC.PostCategory.SharedController Shared = new T4MVC.PostCategory.SharedController();
    }
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class ProductClass
    {
        public readonly string Name = "Product";
        public T4MVC.Product.AdminController Admin = new T4MVC.Product.AdminController();
        public T4MVC.Product.HomeController Home = new T4MVC.Product.HomeController();
        public T4MVC.Product.SearchProductController SearchProduct = new T4MVC.Product.SearchProductController();
        public T4MVC.Product.SharedController Shared = new T4MVC.Product.SharedController();
        public T4MVC.Product.WidgetController Widget = new T4MVC.Product.WidgetController();
    }
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class ProductCategoryClass
    {
        public readonly string Name = "ProductCategory";
        public T4MVC.ProductCategory.AdminController Admin = new T4MVC.ProductCategory.AdminController();
        public T4MVC.ProductCategory.SharedController Shared = new T4MVC.ProductCategory.SharedController();
    }
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class ShoppingCartClass
    {
        public readonly string Name = "ShoppingCart";
        public T4MVC.ShoppingCart.AdminController Admin = new T4MVC.ShoppingCart.AdminController();
        public T4MVC.ShoppingCart.HomeController Home = new T4MVC.ShoppingCart.HomeController();
        public T4MVC.ShoppingCart.SharedController Shared = new T4MVC.ShoppingCart.SharedController();
    }
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class SiteSettingClass
    {
        public readonly string Name = "SiteSetting";
        public T4MVC.SiteSetting.AdminController Admin = new T4MVC.SiteSetting.AdminController();
        public T4MVC.SiteSetting.SharedController Shared = new T4MVC.SiteSetting.SharedController();
    }
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class SlideShowClass
    {
        public readonly string Name = "SlideShow";
        public T4MVC.SlideShow.AdminController Admin = new T4MVC.SlideShow.AdminController();
        public T4MVC.SlideShow.SharedController Shared = new T4MVC.SlideShow.SharedController();
        public T4MVC.SlideShow.WidgetController Widget = new T4MVC.SlideShow.WidgetController();
    }
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class UserClass
    {
        public readonly string Name = "User";
        public T4MVC.User.AdminController Admin = new T4MVC.User.AdminController();
        public T4MVC.User.HomeController Home = new T4MVC.User.HomeController();
        public T4MVC.User.SharedController Shared = new T4MVC.User.SharedController();
    }
}

namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}




namespace Links
{
    
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114


